services:

  frontend:
    build:
      context: .
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "5173:80"

  games:
    build:
      context: ./games
    container_name: portfolio-games
    restart: unless-stopped
    ports:
      - "1337:3001"
