import type { Track } from "../../shared/types";
import { searchTracks } from "./itunes";

/**
 * Songvorschläge: pro Kategorie eine Liste bekannter Interpreten. Für einen Vorschlag
 * werden zwei davon zufällig gesucht (Ergebnisse liegen danach im Zwischenspeicher).
 */
const CATEGORIES: Record<string, string[]> = {
  current: [
    "Taylor Swift",
    "The Weeknd",
    "Dua Lipa",
    "Billie Eilish",
    "Harry Styles",
    "Olivia Rodrigo",
    "Ed Sheeran",
    "Sabrina Carpenter",
    "Bad Bunny",
    "Doja Cat",
    "Post Malone",
    "Ariana Grande",
    "Chappell Roan",
    "Tate McRae",
    "SZA",
    "Miley Cyrus",
    "Lady Gaga",
    "Bruno Mars",
    "Charli XCX",
    "Benson Boone",
    "Hozier",
    "RAYE",
    "Tyla",
    "Shaboozey",
    "Gracie Abrams",
    "Jack Harlow",
    "Central Cee",
    "Megan Thee Stallion",
    "Kendrick Lamar",
    "Sabrina Carpenter",
  ],

  pop: [
    "Lady Gaga",
    "Katy Perry",
    "Rihanna",
    "Bruno Mars",
    "Justin Timberlake",
    "Adele",
    "Coldplay",
    "Maroon 5",
    "Shakira",
    "P!nk",
    "Britney Spears",
    "ABBA",
    "Beyoncé",
    "Justin Bieber",
    "Selena Gomez",
    "Miley Cyrus",
    "Kesha",
    "Christina Aguilera",
    "Jennifer Lopez",
    "One Direction",
    "Jonas Brothers",
    "Backstreet Boys",
    "Spice Girls",
    "The Black Eyed Peas",
    "Nelly Furtado",
    "Kylie Minogue",
    "Carly Rae Jepsen",
    "Ariana Grande",
    "Demi Lovato",
    "Lorde",
    "Sia",
    "Panic! at the Disco",
    "The Chainsmokers",
  ],

  rock: [
    "Queen",
    "AC/DC",
    "Nirvana",
    "Foo Fighters",
    "Red Hot Chili Peppers",
    "Linkin Park",
    "Green Day",
    "The Rolling Stones",
    "Guns N' Roses",
    "Metallica",
    "The Killers",
    "Oasis",
    "Bon Jovi",
    "The Beatles",
    "Led Zeppelin",
    "Pink Floyd",
    "Aerosmith",
    "The Who",
    "U2",
    "Muse",
    "Arctic Monkeys",
    "Kings of Leon",
    "The White Stripes",
    "Fall Out Boy",
    "My Chemical Romance",
    "Paramore",
    "Blink-182",
    "Sum 41",
    "Thirty Seconds to Mars",
    "R.E.M.",
    "Red Hot Chili Peppers",
    "Rage Against the Machine",
    "System of a Down",
    "Evanescence",
    "Placebo",
  ],

  hiphop: [
    "Eminem",
    "Kendrick Lamar",
    "Drake",
    "Kanye West",
    "50 Cent",
    "Snoop Dogg",
    "Jay-Z",
    "Travis Scott",
    "Outkast",
    "Dr. Dre",
    "Nicki Minaj",
    "Macklemore",
    "Tupac",
    "The Notorious B.I.G.",
    "Ice Cube",
    "Nas",
    "Lil Wayne",
    "Future",
    "J. Cole",
    "Cardi B",
    "Megan Thee Stallion",
    "Missy Elliott",
    "N.W.A.",
    "Run-D.M.C.",
    "LL Cool J",
    "Will Smith",
    "Kid Cudi",
    "Tyga",
    "50 Cent",
    "A$AP Rocky",
    "Lil Uzi Vert",
    "21 Savage",
    "Post Malone",
    "Jack Harlow",
    "Central Cee",
  ],

  german: [
    "Die Ärzte",
    "Die Toten Hosen",
    "Peter Fox",
    "Nena",
    "Herbert Grönemeyer",
    "Sido",
    "Cro",
    "Apache 207",
    "Rammstein",
    "Die Fantastischen Vier",
    "Mark Forster",
    "Kraftklub",
    "Seeed",
    "Fettes Brot",
    "Sportfreunde Stiller",
    "Silbermond",
    "Juli",
    "Revolverheld",
    "Clueso",
    "Max Giesinger",
    "Wincent Weiss",
    "Tim Bendzko",
    "Johannes Oerding",
    "Sarah Connor",
    "Helene Fischer",
    "Udo Lindenberg",
    "Westernhagen",
    "Wolfgang Petry",
    "Pur",
    "Die Prinzen",
    "AnnenMayKantereit",
    "LEA",
    "Nina Chuba",
    "Shirin David",
    "Loredana",
    "Bonez MC",
    "RAF Camora",
    "Kontra K",
    "Capital Bra",
    "Trettmann",
    "Casper",
    "Marteria",
  ],

  "80s": [
    "Michael Jackson",
    "Madonna",
    "a-ha",
    "Depeche Mode",
    "Prince",
    "Whitney Houston",
    "Bon Jovi",
    "Eurythmics",
    "Duran Duran",
    "Phil Collins",
    "Cyndi Lauper",
    "Tears for Fears",
    "Queen",
    "George Michael",
    "Wham!",
    "The Police",
    "Dire Straits",
    "Journey",
    "Billy Joel",
    "Bruce Springsteen",
    "David Bowie",
    "AC/DC",
    "Guns N' Roses",
    "Def Leppard",
    "Bryan Adams",
    "Cameo",
    "Rick Astley",
    "Pet Shop Boys",
    "New Order",
    "Simple Minds",
    "Bonnie Tyler",
    "Tina Turner",
    "Alphaville",
    "Modern Talking",
    "Sandra",
    "Falco",
  ],

  "90s": [
    "Backstreet Boys",
    "Spice Girls",
    "Oasis",
    "Nirvana",
    "Britney Spears",
    "No Doubt",
    "TLC",
    "Ace of Base",
    "The Cranberries",
    "Blur",
    "Alanis Morissette",
    "Robbie Williams",
    "Red Hot Chili Peppers",
    "Green Day",
    "R.E.M.",
    "Radiohead",
    "The Offspring",
    "Blink-182",
    "Foo Fighters",
    "Pearl Jam",
    "Metallica",
    "Rage Against the Machine",
    "Destiny's Child",
    "Mariah Carey",
    "Celine Dion",
    "Jennifer Lopez",
    "Christina Aguilera",
    "Aerosmith",
    "Bon Jovi",
    "Dr. Dre",
    "Tupac",
    "The Notorious B.I.G.",
    "Eminem",
    "Will Smith",
    "Coolio",
    "Snoop Dogg",
    "Fugees",
    "Daft Punk",
    "The Prodigy",
    "Scooter",
  ],

  "2000s": [
    "Linkin Park",
    "Beyoncé",
    "Nelly Furtado",
    "The Black Eyed Peas",
    "Avril Lavigne",
    "Usher",
    "OutKast",
    "Gorillaz",
    "Kelly Clarkson",
    "Timbaland",
    "Shakira",
    "Fall Out Boy",
    "Britney Spears",
    "Rihanna",
    "Lady Gaga",
    "Katy Perry",
    "Justin Timberlake",
    "Justin Bieber",
    "Akon",
    "50 Cent",
    "Eminem",
    "Kanye West",
    "Coldplay",
    "Maroon 5",
    "The Killers",
    "Green Day",
    "Foo Fighters",
    "Muse",
    "The White Stripes",
    "Kings of Leon",
    "Arctic Monkeys",
    "Paramore",
    "P!nk",
    "Christina Aguilera",
    "Jason Mraz",
    "Taio Cruz",
    "Flo Rida",
    "David Guetta",
    "Calvin Harris",
    "Avicii",
    "Cascada",
    "Basshunter",
  ],

  electronic: [
    "Daft Punk",
    "Avicii",
    "Calvin Harris",
    "David Guetta",
    "Swedish House Mafia",
    "deadmau5",
    "The Prodigy",
    "The Chemical Brothers",
    "Kygo",
    "Robin Schulz",
    "Martin Garrix",
    "Moby",
    "Tiesto",
    "Armin van Buuren",
    "Skrillex",
    "Diplo",
    "Major Lazer",
    "Marshmello",
    "Zedd",
    "Alan Walker",
    "Hardwell",
    "Afrojack",
    "Steve Aoki",
    "Lost Frequencies",
    "Felix Jaehn",
    "Topic",
    "Purple Disco Machine",
    "Paul Kalkbrenner",
    "Scooter",
    "Faithless",
    "The Prodigy",
    "Justice",
    "Disclosure",
    "Clean Bandit",
    "Rudimental",
    "Sigala",
  ],
};

export const SUGGESTION_CATEGORIES = Object.keys(CATEGORIES);

function sample<T>(list: T[], count: number): T[] {
  const copy = [...list];
  const picked: T[] = [];
  while (copy.length && picked.length < count) {
    picked.push(copy.splice(Math.floor(Math.random() * copy.length), 1)[0]);
  }
  return picked;
}

/** Liefert bis zu acht zufällige bekannte Songs. "surprise" wählt die Kategorie zufällig. */
export async function suggestTracks(category: string): Promise<Track[]> {
  const key = CATEGORIES[category] ? category : sample(SUGGESTION_CATEGORIES, 1)[0];
  const artists = sample(CATEGORIES[key], 2);
  const results = await Promise.all(artists.map((artist) => searchTracks(artist)));

  const tracks = new Map<number, Track>();
  for (const list of results) {
    // Die ersten Treffer einer Interpretensuche sind die bekanntesten Songs.
    for (const track of sample(list.slice(0, 10), 4)) tracks.set(track.id, track);
  }
  return sample([...tracks.values()], 8);
}
